### ISSUE TITLE
Problem on maps

### ISSUE THREAD

**Issue by skinheadxt** [abnerfs/maprestrictions#1]
Hi if it goes to other maps it will bug :(

**Comment by abnerfs** [comment]
If it goes to other maps it will be unloaded. Did you test?

**Comment by skinheadxt** [comment]
It changed to inferno and it was working there too, it had the map restrictions on banana inside the car one by t spawn etc

**Comment by abnerfs** [comment]
You can disable the plugin with map-configs plugin https://forums.alliedmods.net/showthread.php?p=607079
- Install de plugin.
- Move abner_dust2.smx to plugins/disabled folder.
- Create a new file named de_dust2.cfg in cfg/sourcemod/map-cfg.
- Open the file and add the line
  sm plugins load disabled/abner_dust2
- Restart your server 
- Now plugin will be loaded only in dust2.

**Comment by skinheadxt** [comment]
thanks hope you make this for other maps
