### ISSUE TITLE
can u add this decale?

### ISSUE THREAD

**Issue by panikajo** [abnerfs/maprestrictions#4]
![upload_2018-3-12_20-30-18](https://user-images.githubusercontent.com/4964185/52163979-2d464880-26f3-11e9-8b54-0b7dadd93767.png)

**Comment by panikajo** [comment]
[materials.zip](https://github.com/abnerfs/maprestrictions/files/2824381/materials.zip)

**Comment by abnerfs** [comment]
Use [SM File/Folder Downloader and Precacher
](https://forums.alliedmods.net/showthread.php?p=602270) to prechace  your model and edit in sourcemod/data/de_dust2.ini
