### ISSUE TITLE
fence problem

### ISSUE THREAD

**Issue by lazhoroni** [abnerfs/maprestrictions#6]
Just put a fence at the beginning of the round. Some regions are closing if the player comes out from the server in the middle of the round. This is a problem. Can you do it?

**Comment by abnerfs** [comment]
Disable abner_maprestrictions_autorefresh

**Comment by lazhoroni** [comment]
thanks. sometimes A sometimes B. the idea could be good. Random luck. I'll do the work in other maps. I'll share your current ini files.
