### ISSUE TITLE
could be used for CS:S?

### ISSUE THREAD

**Issue by matheuseduardo** [abnerfs/maprestrictions#7]
I think, looking at your code, could be used also for CS:S.
What's is the best way to check maps coordinates to write in .ini?

**Comment by abnerfs** [comment]
definitively could be used in css, the process to write an .ini is totally manual, basically try and error using cl_showpos 1, I wil see if i can provide a .ini file for css at leat for dust2

**Comment by abnerfs** [comment]
Apparently it worked, can you try the version in [develop](https://github.com/abnerfs/maprestrictions/tree/develop) branch?

![image](https://user-images.githubusercontent.com/14078661/133135712-b6a1ad84-3f70-4d25-87f6-abededa73098.png)

**Comment by matheuseduardo** [comment]
excelent work! I'll give some try tonight! thx in advance!
